### PR TITLE
[Dist] Add support for customizable MPI / NCCL communicators - Phase 2

### PR DESCRIPTION
**Pull request by Tonny-Gu**
## Description ##

- [x] Extend API: `RequestDistributed`
- [x] Make `CommunicatorPool` thread-local
   - To make it thread-safe and support potential communicators that coordinate multiple threads

## Checklist ##

- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

cc @awslabs/raf-reviewer

### CODE REVIEW

**Review by comaniac — COMMENTED** [review]
Overall LGTM.
Do we need a test case?

@hgt312 @zhen-jia please help review this PR.

**Comment by Tonny-Gu** [comment]
> Overall LGTM. Do we need a test case?
> 
> @hgt312 @zhen-jia please help review this PR.

For `RequestDistributed`, the existing unit tests can cover this case. 
As for `thread-local CommPool`, it should be fine as the modification is very simple and trivial.

**Review by zhen-jia — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
Thanks @Tonny-Gu @hgt312 @zhen-jia

**Pull request merged**
