### PR TITLE
[BUGFIX] Fix group_reduce_scatter unit test

### PR DESCRIPTION
**Pull request by whbldhwj**
## Description ##
Fix one unit test (test_group_reduce_scatter), which requires exact 2 processes to succeed.

## Checklist ##

- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

cc @awslabs/raf-reviewer

### CODE REVIEW

**Comment by comaniac** [comment]
cc @zhen-jia @zachzzc @hgt312

**Comment by zachzzc** [comment]
It looks like the test is hard coded 
`n_ones = np.ones(shape=(2, 4), dtype="float32")`

Can you revise (2, 4) to be generated by rank ?

**Review by zhen-jia — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
@whbldhwj could you address the comment from @zachzzc and fix the CI?

**Pull request closed without merging**
